"""updated poi

Revision ID: 1a373dc6361a
Revises: 156eeb7be00a
Create Date: 2014-12-07 07:11:11.958593

"""

# revision identifiers, used by Alembic.
revision = '1a373dc6361a'
down_revision = '156eeb7be00a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    op.add_column('points_of_interests', sa.Column('bspaid', sa.String(length=40), nullable=True))
    op.add_column('points_of_interests', sa.Column('elev_ft', sa.Float(), nullable=True))
    op.add_column('points_of_interests', sa.Column('poi_class', sa.String(length=40), nullable=True))
    op.add_column('points_of_interests', sa.Column('poi_group', sa.String(length=40), nullable=True))
    op.add_column('points_of_interests', sa.Column('poi_type', sa.String(length=40), nullable=True))
    op.add_column('points_of_interests', sa.Column('poiid', sa.Integer(), nullable=True))
    op.add_column('points_of_interests', sa.Column('public_shar', sa.Boolean(), nullable=True))
    op.add_column('points_of_interests', sa.Column('remark', sa.Text(), nullable=True))
    op.add_column('points_of_interests', sa.Column('site_capacity', sa.Integer(), nullable=True))
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    op.drop_column('points_of_interests', 'site_capacity')
    op.drop_column('points_of_interests', 'remark')
    op.drop_column('points_of_interests', 'public_shar')
    op.drop_column('points_of_interests', 'poiid')
    op.drop_column('points_of_interests', 'poi_type')
    op.drop_column('points_of_interests', 'poi_group')
    op.drop_column('points_of_interests', 'poi_class')
    op.drop_column('points_of_interests', 'elev_ft')
    op.drop_column('points_of_interests', 'bspaid')
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    ### end Alembic commands ###
