"""added Trail.status

Revision ID: 24286ef61686
Revises: 4635aa88d8bf
Create Date: 2014-12-03 18:13:23.138629

"""

# revision identifiers, used by Alembic.
revision = '24286ef61686'
down_revision = '4635aa88d8bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=40), nullable=True))
        #batch_op.drop_index('idx_trail_geom')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        #batch_op.create_index('idx_trail_geom', ['geom'], unique=False)
        batch_op.drop_column('status')

    ### end Alembic commands ###
