"""trail.geom to multi

Revision ID: 2a237f9c430f
Revises: 2dec8c5c859d
Create Date: 2014-12-03 19:24:46.501525

"""

# revision identifiers, used by Alembic.
revision = '2a237f9c430f'
down_revision = '2dec8c5c859d'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('geom')

    ### end Alembic commands ###
