"""ava incident and involved

Revision ID: 2cd97a95cea1
Revises: 56bc7e72abc9
Create Date: 2014-12-07 10:20:36.370849

"""

# revision identifiers, used by Alembic.
revision = '2cd97a95cea1'
down_revision = '56bc7e72abc9'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avalanche_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.DateTime(), nullable=True),
    sa.Column('occurence_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(length=40), nullable=True),
    sa.Column('trigger', sa.String(length=40), nullable=True),
    sa.Column('trigger_add', sa.String(length=40), nullable=True),
    sa.Column('av_problem', sa.String(length=40), nullable=True),
    sa.Column('av_type', sa.String(length=40), nullable=True),
    sa.Column('weak_layer', sa.String(length=40), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('vertical', sa.Float(), nullable=True),
    sa.Column('slope_angle', sa.Float(), nullable=True),
    sa.Column('people_caught', sa.Integer(), nullable=True),
    sa.Column('people_carried', sa.Integer(), nullable=True),
    sa.Column('people_buried_part', sa.Integer(), nullable=True),
    sa.Column('people_buried_full', sa.Integer(), nullable=True),
    sa.Column('snow_profile', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crown', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=926919), nullable=True),
    sa.Column('bed_surface', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=926919), nullable=True),
    sa.Column('debris_field', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=926919), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['avalanche_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avalanche_involved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first', sa.String(length=40), nullable=True),
    sa.Column('last', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('observed', sa.Boolean(), nullable=True),
    sa.Column('group', sa.Boolean(), nullable=True),
    sa.Column('caught', sa.Boolean(), nullable=True),
    sa.Column('carried', sa.Boolean(), nullable=True),
    sa.Column('burried', sa.Boolean(), nullable=True),
    sa.Column('rescuer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['avalanche_ins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'avalanche_paths', sa.Column('aspect', sa.String(length=40), nullable=True))
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    op.drop_column(u'avalanche_paths', 'aspect')
    op.drop_table('avalanche_involved')
    op.drop_table('avalanche_ins')
    ### end Alembic commands ###
