"""removed Trail Geometry

Revision ID: 2cf6c7c1f0d7
Revises: 4c1635dc21ed
Create Date: 2014-12-05 18:12:03.976594

"""

# revision identifiers, used by Alembic.
revision = '2cf6c7c1f0d7'
down_revision = '4c1635dc21ed'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('POI', schema=None) as batch_op:
     #   batch_op.drop_index('idx_POI_point')

    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('geom')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type=u'MULTILINESTRING', srid=926919), autoincrement=False, nullable=True))

    #with op.batch_alter_table('POI', schema=None) as batch_op:
    #    batch_op.create_index('idx_POI_point', ['point'], unique=False)

    ### end Alembic commands ###
