"""remove trail.geom

Revision ID: 2dec8c5c859d
Revises: 24286ef61686
Create Date: 2014-12-03 19:23:31.323177

"""

# revision identifiers, used by Alembic.
revision = '2dec8c5c859d'
down_revision = '24286ef61686'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_index('idx_trail_geom')
        batch_op.drop_column('geom')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type=u'LINESTRING'), autoincrement=False, nullable=True))
        batch_op.create_index('idx_trail_geom', ['geom'], unique=False)

    ### end Alembic commands ###
