"""trail.geom removed to update srid

Revision ID: 313d31ec9947
Revises: 2a237f9c430f
Create Date: 2014-12-03 19:51:59.212681

"""

# revision identifiers, used by Alembic.
revision = '313d31ec9947'
down_revision = '2a237f9c430f'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('geom')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type=u'MULTILINESTRING'), autoincrement=False, nullable=True))

    ### end Alembic commands ###
