"""snowpit and photo incident foreign key

Revision ID: 33f86343dd78
Revises: 32e262402de6
Create Date: 2014-12-07 11:40:22.795922

"""

# revision identifiers, used by Alembic.
revision = '33f86343dd78'
down_revision = '32e262402de6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    op.add_column('photoss', sa.Column('incident_id', sa.Integer(), nullable=True))
    #op.drop_index('idx_photoss_location', table_name='photoss')
    op.create_foreign_key(None, 'photoss', 'avalanche_ins', ['incident_id'], ['id'])
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    op.add_column('snowpits', sa.Column('incident_id', sa.Integer(), nullable=True))
    #op.drop_index('idx_snowpits_location', table_name='snowpits')
    op.create_foreign_key(None, 'snowpits', 'avalanche_ins', ['incident_id'], ['id'])
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    op.drop_constraint(None, 'snowpits', type_='foreignkey')
    #op.create_index('idx_snowpits_location', 'snowpits', ['location'], unique=False)
    op.drop_column('snowpits', 'incident_id')
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    op.drop_constraint(None, 'photoss', type_='foreignkey')
    #op.create_index('idx_photoss_location', 'photoss', ['location'], unique=False)
    op.drop_column('photoss', 'incident_id')
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    ### end Alembic commands ###
