"""trail.geom update srid

Revision ID: eba193087da
Revises: 313d31ec9947
Create Date: 2014-12-03 19:53:02.796458

"""

# revision identifiers, used by Alembic.
revision = 'eba193087da'
down_revision = '313d31ec9947'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=926919), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('geom')

    ### end Alembic commands ###
