"""avalanche_ins_photos m-2-m

Revision ID: 129da6a086ef
Revises: 3c96906ee661
Create Date: 2015-01-04 21:08:25.777184

"""

# revision identifiers, used by Alembic.
revision = '129da6a086ef'
down_revision = '3c96906ee661'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avalanche_ins_photo',
    sa.Column('avalanche_ins_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avalanche_ins_id'], ['avalanche_ins.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photoss.id'], )
    )
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_photoss_location', table_name='photoss')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_snowpits_location', table_name='snowpits')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_snowpits_location', 'snowpits', ['location'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_photoss_location', 'photoss', ['location'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    op.drop_table('avalanche_ins_photo')
    ### end Alembic commands ###
