"""renamed trail and poi added avalanche path

Revision ID: 156eeb7be00a
Revises: 56afb969b589
Create Date: 2014-12-07 06:44:55.956914

"""

# revision identifiers, used by Alembic.
revision = '156eeb7be00a'
down_revision = '56afb969b589'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=926919), nullable=True),
    sa.Column('use_type', sa.String(length=40), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('skitrail', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('length_mi', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('pubshare', sa.Boolean(), nullable=True),
    sa.Column('gpsupdate', sa.Date(), nullable=True),
    sa.Column('gpsunit', sa.String(length=40), nullable=True),
    sa.Column('gpsuser', sa.String(length=40), nullable=True),
    sa.Column('bspaid', sa.String(length=40), nullable=True),
    sa.Column('tsid', sa.String(length=40), nullable=True),
    sa.Column('display_wu', sa.Boolean(), nullable=True),
    sa.Column('display_wn', sa.Boolean(), nullable=True),
    sa.Column('ttype', sa.String(length=40), nullable=True),
    sa.Column('season', sa.String(length=40), nullable=True),
    sa.Column('shape_leng', sa.Float(), nullable=True),
    sa.Column('tclass', sa.String(length=40), nullable=True),
    sa.Column('maintclass', sa.String(length=40), nullable=True),
    sa.Column('slength', sa.Float(), nullable=True),
    sa.Column('min_slope', sa.Float(), nullable=True),
    sa.Column('max_slope', sa.Float(), nullable=True),
    sa.Column('avg_slope', sa.Float(), nullable=True),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avalanche_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=926919), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_of_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=926919), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('POI')
    op.drop_table('trail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('use_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skitrail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('length_mi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('display', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pubshare', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gpsupdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gpsunit', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('gpsuser', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('bspaid', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('tsid', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('display_wu', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_wn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ttype', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('shape_leng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tclass', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('maintclass', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('slength', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_slope', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_slope', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_slope', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('length_ft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type=u'MULTILINESTRING'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'trail_pkey')
    )
    op.create_table('POI',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"POI_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type=u'POINT'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'POI_pkey')
    )
    op.drop_table('points_of_interests')
    op.drop_table('avalanche_paths')
    op.drop_table('trails')
    ### end Alembic commands ###
