"""initial migration

Revision ID: 1ee32132dcf
Revises: None
Create Date: 2014-12-03 16:52:17.488321

"""

# revision identifiers, used by Alembic.
revision = '1ee32132dcf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('first', sa.String(length=80), nullable=True),
    sa.Column('last', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('observer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('for_temp_high', sa.Integer(), nullable=True),
    sa.Column('for_temp_low', sa.Integer(), nullable=True),
    sa.Column('trail_comment', sa.Text(), nullable=True),
    sa.Column('for_today', sa.Text(), nullable=True),
    sa.Column('for_tomorrow', sa.Text(), nullable=True),
    sa.Column('for_long', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sky', sa.String(length=40), nullable=True),
    sa.Column('precip_type', sa.String(length=40), nullable=True),
    sa.Column('precip_rate', sa.String(length=40), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_present', sa.Float(), nullable=True),
    sa.Column('temp_trend', sa.String(length=40), nullable=True),
    sa.Column('pressure_present', sa.Float(), nullable=True),
    sa.Column('pressure_trend', sa.String(length=40), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=40), nullable=True),
    sa.Column('wind_gust_max', sa.Float(), nullable=True),
    sa.Column('rain_24', sa.Float(), nullable=True),
    sa.Column('snow_depth', sa.Float(), nullable=True),
    sa.Column('snow_24', sa.Float(), nullable=True),
    sa.Column('snow_storm', sa.Float(), nullable=True),
    sa.Column('snow_8_temp', sa.Float(), nullable=True),
    sa.Column('snow_density', sa.Float(), nullable=True),
    sa.Column('snow_foot_pen', sa.Float(), nullable=True),
    sa.Column('snow_ram_pen', sa.Float(), nullable=True),
    sa.Column('snow_surface_form', sa.String(length=80), nullable=True),
    sa.Column('snow_surface_size', sa.Float(), nullable=True),
    sa.Column('snow_blowing_extent', sa.String(length=40), nullable=True),
    sa.Column('snow_water_equil', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_observations')
    op.drop_table('weather_forecasts')
    op.drop_table('users')
    ### end Alembic commands ###
