"""add photo and snowpit

Revision ID: 32e262402de6
Revises: 3797e4d2c807
Create Date: 2014-12-07 11:37:21.804891

"""

# revision identifiers, used by Alembic.
revision = '32e262402de6'
down_revision = '3797e4d2c807'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snowpits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=926919), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photoss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=926919), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    op.drop_table('photoss')
    op.drop_table('snowpits')
    ### end Alembic commands ###
