"""avalanche_ins added display killed injuried size summary activity travel rescuer

Revision ID: 37263f5a2241
Revises: 26bafe6e0145
Create Date: 2015-01-04 21:30:26.175965

"""

# revision identifiers, used by Alembic.
revision = '37263f5a2241'
down_revision = '26bafe6e0145'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avalanche_ins', sa.Column('display', sa.Boolean(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('group_activity', sa.String(length=40), nullable=True))
    op.add_column('avalanche_ins', sa.Column('group_travel', sa.String(length=40), nullable=True))
    op.add_column('avalanche_ins', sa.Column('people_injured', sa.Integer(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('people_killed', sa.Integer(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('people_rescuer', sa.Integer(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('size_desctructive', sa.Float(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('size_relative', sa.Float(), nullable=True))
    op.add_column('avalanche_ins', sa.Column('summary', sa.Text(), nullable=True))
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_photoss_location', table_name='photoss')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_snowpits_location', table_name='snowpits')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_snowpits_location', 'snowpits', ['location'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_photoss_location', 'photoss', ['location'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    op.drop_column('avalanche_ins', 'summary')
    op.drop_column('avalanche_ins', 'size_relative')
    op.drop_column('avalanche_ins', 'size_desctructive')
    op.drop_column('avalanche_ins', 'people_rescuer')
    op.drop_column('avalanche_ins', 'people_killed')
    op.drop_column('avalanche_ins', 'people_injured')
    op.drop_column('avalanche_ins', 'group_travel')
    op.drop_column('avalanche_ins', 'group_activity')
    op.drop_column('avalanche_ins', 'display')
    ### end Alembic commands ###
