"""involved geo and incident name

Revision ID: 3797e4d2c807
Revises: 2cd97a95cea1
Create Date: 2014-12-07 11:11:58.761632

"""

# revision identifiers, used by Alembic.
revision = '3797e4d2c807'
down_revision = '2cd97a95cea1'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avalanche_ins', sa.Column('name', sa.String(length=80), nullable=True))
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    op.add_column('avalanche_involved', sa.Column('locations', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=926919), nullable=True))
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    op.drop_column('avalanche_involved', 'locations')
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    op.drop_column('avalanche_ins', 'name')
    ### end Alembic commands ###
