"""initial WeatherFor

Revision ID: 3de4ee3e8096
Revises: 24bcf1f51901
Create Date: 2014-12-02 23:11:28.753827

"""

# revision identifiers, used by Alembic.
revision = '3de4ee3e8096'
down_revision = '24bcf1f51901'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('for_temp_high', sa.Integer(), nullable=True),
    sa.Column('for_temp_low', sa.Integer(), nullable=True),
    sa.Column('trail_comment', sa.Text(), nullable=True),
    sa.Column('for_today', sa.Text(), nullable=True),
    sa.Column('for_tomorrow', sa.Text(), nullable=True),
    sa.Column('for_long', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['observer_id'], ['observers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    #)
    op.drop_table('weather_forecasts')
    ### end Alembic commands ###
