"""added Trail

Revision ID: 4635aa88d8bf
Revises: 1ee32132dcf
Create Date: 2014-12-03 17:50:09.442365

"""

# revision identifiers, used by Alembic.
revision = '4635aa88d8bf'
down_revision = '1ee32132dcf'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('use_type', sa.String(length=40), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('skitrail', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('length_mi', sa.Float(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('pubshare', sa.Boolean(), nullable=True),
    sa.Column('gpsupdate', sa.Date(), nullable=True),
    sa.Column('gpsunit', sa.String(length=40), nullable=True),
    sa.Column('gpsuser', sa.String(length=40), nullable=True),
    sa.Column('bspaid', sa.String(length=40), nullable=True),
    sa.Column('tsid', sa.String(length=40), nullable=True),
    sa.Column('display_wu', sa.Boolean(), nullable=True),
    sa.Column('display_wn', sa.Boolean(), nullable=True),
    sa.Column('ttype', sa.String(length=40), nullable=True),
    sa.Column('season', sa.String(length=40), nullable=True),
    sa.Column('shape_leng', sa.Float(), nullable=True),
    sa.Column('tclass', sa.String(length=40), nullable=True),
    sa.Column('maintclass', sa.String(length=40), nullable=True),
    sa.Column('slength', sa.Float(), nullable=True),
    sa.Column('min_slope', sa.Float(), nullable=True),
    sa.Column('max_slope', sa.Float(), nullable=True),
    sa.Column('avg_slope', sa.Float(), nullable=True),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail')
    ### end Alembic commands ###
