"""testing POI

Revision ID: 4c1635dc21ed
Revises: eba193087da
Create Date: 2014-12-05 17:52:58.380773

"""

# revision identifiers, used by Alembic.
revision = '4c1635dc21ed'
down_revision = 'eba193087da'

from alembic import op
import sqlalchemy as sa
import flask_admin

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('point', flask_admin.contrib.geoa.sqltypes.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('POI')
    ### end Alembic commands ###
