"""added Trail.Geometry without srid

Revision ID: 56afb969b589
Revises: 2cf6c7c1f0d7
Create Date: 2014-12-05 18:13:55.512637

"""

# revision identifiers, used by Alembic.
revision = '56afb969b589'
down_revision = '2cf6c7c1f0d7'

from alembic import op
import sqlalchemy as sa
import flask_admin


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('POI', schema=None) as batch_op:
    #    batch_op.drop_index('idx_POI_point')

    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', flask_admin.contrib.geoa.sqltypes.Geometry(geometry_type='MULTILINESTRING'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('geom')

    #with op.batch_alter_table('POI', schema=None) as batch_op:
    #    batch_op.create_index('idx_POI_point', ['point'], unique=False)

    ### end Alembic commands ###
