"""poi.facility_id

Revision ID: 56bc7e72abc9
Revises: 143238c281a7
Create Date: 2014-12-07 07:27:06.428657

"""

# revision identifiers, used by Alembic.
revision = '56bc7e72abc9'
down_revision = '143238c281a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    op.add_column('points_of_interests', sa.Column('facility_id', sa.Integer(), nullable=True))
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    op.drop_column('points_of_interests', 'facility_id')
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    ### end Alembic commands ###
