"""added avalanche in problems association

Revision ID: 76489d1e0d5
Revises: 959c31308e2
Create Date: 2014-12-22 07:22:08.662961

"""

# revision identifiers, used by Alembic.
revision = '76489d1e0d5'
down_revision = '959c31308e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avalanche_ob_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('aspects', sa.String(length=80), nullable=True),
    sa.Column('likelyhood', sa.String(length=40), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('trend', sa.String(length=40), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['avalanche_ins.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['avalanche_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_index('idx_avalanche_ins_bed_surface', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_crown', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_ins_debris_field', table_name='avalanche_ins')
    #op.drop_index('idx_avalanche_paths_path', table_name='avalanche_paths')
    #op.drop_index('idx_photoss_location', table_name='photoss')
    #op.drop_index('idx_points_of_interests_point', table_name='points_of_interests')
    #op.drop_index('idx_snowpits_location', table_name='snowpits')
    #op.drop_index('idx_trails_geom', table_name='trails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_trails_geom', 'trails', ['geom'], unique=False)
    #op.create_index('idx_snowpits_location', 'snowpits', ['location'], unique=False)
    #op.create_index('idx_points_of_interests_point', 'points_of_interests', ['point'], unique=False)
    #op.create_index('idx_photoss_location', 'photoss', ['location'], unique=False)
    #op.create_index('idx_avalanche_paths_path', 'avalanche_paths', ['path'], unique=False)
    #op.create_index('idx_avalanche_ins_debris_field', 'avalanche_ins', ['debris_field'], unique=False)
    #op.create_index('idx_avalanche_ins_crown', 'avalanche_ins', ['crown'], unique=False)
    #op.create_index('idx_avalanche_ins_bed_surface', 'avalanche_ins', ['bed_surface'], unique=False)
    op.drop_table('avalanche_ob_problem')
    ### end Alembic commands ###
