#!/bin/bash

##############################################################
### Need to set environmental variables for flask to run   ###
### in host-export. Use host-export-example                ###
##############################################################

# gunicorn starter from http://prakhar.me/articles/flask-on-nginx-and-gunicorn/

# Local variables

NAME="data.Baxter"
FLASKDIR=/home/www/baxter-flask
VENVDIR=/home/www/env
USER=baxter-www
GROUP=baxter-www
NUM_WORKERS=5
LOG_FILE=/home/www/logs/baxter-flask/gunicorn.log

# Exported variables
source $FLASKDIR"/server-config/host-export"

echo "Starting $NAME"

# activate the virtualenv
cd $VENVDIR
source bin/activate

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

exec gunicorn wsgi:app -b 127.0.0.1:8000 \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug
  --access-logfile $LOG_FILE
